version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
    restart:
      always
  grafana:
    image: grafana:local
    container_name: grafana
    ports:
      - 3001:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-storage:/var/lib/grafana
    restart:
      always
  etl:
    image: etl:latest
    container_name: etl
    environment: 
      - DB_HOST=influxdb
    depends_on:
      - influxdb
    restart:
      always
volumes:
  influxdb:
  grafana-storage: