apiVersion: 1
datasources:
  - name: covidDb
    type: influxdb
    access: proxy
    database: covid
    editable: true
    url: http://localhost:8086
    jsonData:
      timeInterval: "15s"
  - name: marketDb
    type: influxdb
    access: proxy
    database: market
    editable: true
    url: http://localhost:8086
    jsonData:
      timeInterval: "15s"