apiVersion: 1
datasources:
  - name: covidDb
    type: influxdb
    access: proxy
    database: covid
    url: http://influxdb:8086
    jsonData:
      timeInterval: "15s"
  - name: marketDb
    type: influxdb
    access: proxy
    database: market
    url: http://influxdb:8086
    jsonData:
      timeInterval: "15s"