name: Continuous deployment

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: turingcomplet.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/checkout@v2
    - name: Build and push images
      run: |
        docker build . -t turingcomplet.azurecr.io/etl:latest
        docker build grafana -t turingcomplet.azurecr.io/grafana:latest
        docker push turingcomplet.azurecr.io/etl:latest
        docker push turingcomplet.azurecr.io/grafana:latest
        az container delete --name pandemicMonitor --resource-group ${{ secrets.RESOURCE_GROUP }}
        az container create --resource-group ${{ secrets.RESOURCE_GROUP }} --file deploy-aci.yaml
